[package]
name = "dot-trove"
description = "Dotfile management system"
version = "0.1.0"
edition = "2021"
license = "MIT"
homepage = "https://github.com/yudjinn/dot-trove"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
